package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-12-10T19:35:23.049-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "Comunicacion.Comunicacion", name = "Comunicacion")
@XmlSeeAlso({ObjectFactory.class})
public interface Comunicacion {

    @WebResult(name = "wsApagarGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsApagarGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsApagarGrupoActuadores")
    @WebMethod(action = "wsApagarGrupoActuadores")
    @ResponseWrapper(localName = "wsApagarGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsApagarGrupoActuadoresResponse")
    public ws.ResultadoAccionWS wsApagarGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo
    );

    @WebResult(name = "wsEncenderGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEncenderGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEncenderGrupoActuadores")
    @WebMethod(action = "wsEncenderGrupoActuadores")
    @ResponseWrapper(localName = "wsEncenderGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEncenderGrupoActuadoresResponse")
    public ws.ResultadoAccionWS wsEncenderGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo
    );

    @WebResult(name = "wsCambiarPosicionGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCambiarPosicionGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCambiarPosicionGrupoActuadores")
    @WebMethod(action = "wsCambiarPosicionGrupoActuadores")
    @ResponseWrapper(localName = "wsCambiarPosicionGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCambiarPosicionGrupoActuadoresResponse")
    public ws.ResultadoAccionWS wsCambiarPosicionGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo,
        @WebParam(name = "nroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPosicion
    );

    @WebResult(name = "wsCambiarEstadoSistemaResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCambiarEstadoSistema", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCambiarEstadoSistema")
    @WebMethod(action = "wsCambiarEstadoSistema")
    @ResponseWrapper(localName = "wsCambiarEstadoSistemaResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCambiarEstadoSistemaResponse")
    public ws.Mensaje wsCambiarEstadoSistema(
        @WebParam(name = "estado", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String estado
    );

    @WebResult(name = "wsCrearFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearFactor", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearFactor")
    @WebMethod(action = "wsCrearFactor")
    @ResponseWrapper(localName = "wsCrearFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearFactorResponse")
    public ws.ResultadoCreacionWS wsCrearFactor(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "unidad", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String unidad,
        @WebParam(name = "valorMin", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valorMin,
        @WebParam(name = "valorMax", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valorMax,
        @WebParam(name = "umbral", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger umbral
    );

    @WebResult(name = "wsAgregarSensorPosicionActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarSensorPosicionActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarSensorPosicionActuadorAvance")
    @WebMethod(action = "wsAgregarSensorPosicionActuadorAvance")
    @ResponseWrapper(localName = "wsAgregarSensorPosicionActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarSensorPosicionActuadorAvanceResponse")
    public ws.ResultadoCreacionWS wsAgregarSensorPosicionActuadorAvance(
        @WebParam(name = "idSensor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idSensor,
        @WebParam(name = "idActuadorAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idActuadorAvance,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion
    );

    @WebResult(name = "wsEliminarFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarFactor", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarFactor")
    @WebMethod(action = "wsEliminarFactor")
    @ResponseWrapper(localName = "wsEliminarFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarFactorResponse")
    public ws.Mensaje wsEliminarFactor(
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsReestablecerActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsReestablecerActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsReestablecerActuadorAvance")
    @WebMethod(action = "wsReestablecerActuadorAvance")
    @ResponseWrapper(localName = "wsReestablecerActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsReestablecerActuadorAvanceResponse")
    public ws.Mensaje wsReestablecerActuadorAvance(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion
    );

    @WebResult(name = "wsAgregarPosicionActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarPosicionActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarPosicionActuadorAvance")
    @WebMethod(action = "wsAgregarPosicionActuadorAvance")
    @ResponseWrapper(localName = "wsAgregarPosicionActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarPosicionActuadorAvanceResponse")
    public ws.ResultadoCreacionWS wsAgregarPosicionActuadorAvance(
        @WebParam(name = "idActuadorAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idActuadorAvance,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion,
        @WebParam(name = "descripcion", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String descripcion,
        @WebParam(name = "valor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valor
    );

    @WebResult(name = "wsCrearPlacaAuxiliarResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearPlacaAuxiliar", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearPlacaAuxiliar")
    @WebMethod(action = "wsCrearPlacaAuxiliar")
    @ResponseWrapper(localName = "wsCrearPlacaAuxiliarResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearPlacaAuxiliarResponse")
    public ws.ResultadoCreacionWS wsCrearPlacaAuxiliar(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "nroSerie", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nroSerie,
        @WebParam(name = "idTipoPlaca", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPlaca,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre
    );

    @WebResult(name = "wsCrearTipoActuadorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearTipoActuador", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearTipoActuador")
    @WebMethod(action = "wsCrearTipoActuador")
    @ResponseWrapper(localName = "wsCrearTipoActuadorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearTipoActuadorResponse")
    public ws.ResultadoCreacionWS wsCrearTipoActuador(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre
    );

    @WebResult(name = "wsAgregarFilaPerfilActivacionResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarFilaPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarFilaPerfilActivacion")
    @WebMethod(action = "wsAgregarFilaPerfilActivacion")
    @ResponseWrapper(localName = "wsAgregarFilaPerfilActivacionResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsAgregarFilaPerfilActivacionResponse")
    public ws.ResultadoCreacionWS wsAgregarFilaPerfilActivacion(
        @WebParam(name = "idPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPerfilActivacion,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores,
        @WebParam(name = "estado", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String estado
    );

    @WebResult(name = "wsEliminarNivelSeveridadResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarNivelSeveridad")
    @WebMethod(action = "wsEliminarNivelSeveridad")
    @ResponseWrapper(localName = "wsEliminarNivelSeveridadResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarNivelSeveridadResponse")
    public ws.Mensaje wsEliminarNivelSeveridad(
        @WebParam(name = "idNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idNivelSeveridad
    );

    @WebResult(name = "wsLecturaFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsLecturaFactor", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsLecturaFactor")
    @WebMethod(action = "wsLecturaFactor")
    @ResponseWrapper(localName = "wsLecturaFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsLecturaFactorResponse")
    public ws.ResultadoLecturaWS wsLecturaFactor(
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsEliminarGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarGrupoActuadores")
    @WebMethod(action = "wsEliminarGrupoActuadores")
    @ResponseWrapper(localName = "wsEliminarGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarGrupoActuadoresResponse")
    public ws.Mensaje wsEliminarGrupoActuadores(
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearActuadorAvance")
    @WebMethod(action = "wsCrearActuadorAvance")
    @ResponseWrapper(localName = "wsCrearActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearActuadorAvanceResponse")
    public ws.ResultadoCreacionWS wsCrearActuadorAvance(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "posicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger posicion,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idTipoActuador", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoActuador,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "nroPuertoRetroceso", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuertoRetroceso,
        @WebParam(name = "tipoPuertoRetroceso", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger tipoPuertoRetroceso,
        @WebParam(name = "tiempoEntrePosiciones", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger tiempoEntrePosiciones,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearActuadorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearActuador", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearActuador")
    @WebMethod(action = "wsCrearActuador")
    @ResponseWrapper(localName = "wsCrearActuadorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearActuadorResponse")
    public ws.ResultadoCreacionWS wsCrearActuador(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idTipoActuador", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoActuador,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearGrupoActuadores")
    @WebMethod(action = "wsCrearGrupoActuadores")
    @ResponseWrapper(localName = "wsCrearGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearGrupoActuadoresResponse")
    public ws.ResultadoCreacionWS wsCrearGrupoActuadores(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "deAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String deAvance
    );

    @WebResult(name = "wsCrearSensorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearSensor", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearSensor")
    @WebMethod(action = "wsCrearSensor")
    @ResponseWrapper(localName = "wsCrearSensorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearSensorResponse")
    public ws.ResultadoCreacionWS wsCrearSensor(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "formulaConversion", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String formulaConversion,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsEliminarFilaPerfilActivacionResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarFilaPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarFilaPerfilActivacion")
    @WebMethod(action = "wsEliminarFilaPerfilActivacion")
    @ResponseWrapper(localName = "wsEliminarFilaPerfilActivacionResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarFilaPerfilActivacionResponse")
    public ws.Mensaje wsEliminarFilaPerfilActivacion(
        @WebParam(name = "idPerfil", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPerfil,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsEliminarDispositivoResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarDispositivo", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarDispositivo")
    @WebMethod(action = "wsEliminarDispositivo")
    @ResponseWrapper(localName = "wsEliminarDispositivoResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsEliminarDispositivoResponse")
    public ws.Mensaje wsEliminarDispositivo(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo
    );

    @WebResult(name = "wsReestablecerEstadoAlertaDispositivoResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsReestablecerEstadoAlertaDispositivo", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsReestablecerEstadoAlertaDispositivo")
    @WebMethod(action = "wsReestablecerEstadoAlertaDispositivo")
    @ResponseWrapper(localName = "wsReestablecerEstadoAlertaDispositivoResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsReestablecerEstadoAlertaDispositivoResponse")
    public ws.Mensaje wsReestablecerEstadoAlertaDispositivo(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo
    );

    @WebResult(name = "wsCrearNivelSeveridadResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearNivelSeveridad")
    @WebMethod(action = "wsCrearNivelSeveridad")
    @ResponseWrapper(localName = "wsCrearNivelSeveridadResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearNivelSeveridadResponse")
    public ws.ResultadoCreacionWS wsCrearNivelSeveridad(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor,
        @WebParam(name = "prioridad", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger prioridad,
        @WebParam(name = "rangoMinimo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger rangoMinimo,
        @WebParam(name = "rangoMaximo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger rangoMaximo
    );

    @WebResult(name = "wsCrearTipoPlacaResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearTipoPlaca", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearTipoPlaca")
    @WebMethod(action = "wsCrearTipoPlaca")
    @ResponseWrapper(localName = "wsCrearTipoPlacaResponse", targetNamespace = "Comunicacion.Comunicacion", className = "ws.WsCrearTipoPlacaResponse")
    public ws.ResultadoCreacionWS wsCrearTipoPlaca(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre
    );
}
