package uy.com.ceoyphoibe.SGIA.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-12-14T18:04:34.215-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "Comunicacion.Comunicacion", name = "Comunicacion")
@XmlSeeAlso({ObjectFactory.class})
public interface Comunicacion {

    @WebResult(name = "wsApagarGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsApagarGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsApagarGrupoActuadores")
    @WebMethod(action = "wsApagarGrupoActuadores")
    @ResponseWrapper(localName = "wsApagarGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsApagarGrupoActuadoresResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoAccionWS wsApagarGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo
    );

    @WebResult(name = "wsEncenderGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEncenderGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEncenderGrupoActuadores")
    @WebMethod(action = "wsEncenderGrupoActuadores")
    @ResponseWrapper(localName = "wsEncenderGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEncenderGrupoActuadoresResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoAccionWS wsEncenderGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo
    );

    @WebResult(name = "wsCambiarPosicionGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCambiarPosicionGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCambiarPosicionGrupoActuadores")
    @WebMethod(action = "wsCambiarPosicionGrupoActuadores")
    @ResponseWrapper(localName = "wsCambiarPosicionGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCambiarPosicionGrupoActuadoresResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoAccionWS wsCambiarPosicionGrupoActuadores(
        @WebParam(name = "idGrupo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupo,
        @WebParam(name = "nroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPosicion
    );

    @WebResult(name = "wsCambiarEstadoSistemaResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCambiarEstadoSistema", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCambiarEstadoSistema")
    @WebMethod(action = "wsCambiarEstadoSistema")
    @ResponseWrapper(localName = "wsCambiarEstadoSistemaResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCambiarEstadoSistemaResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsCambiarEstadoSistema(
        @WebParam(name = "estado", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String estado
    );

    @WebResult(name = "wsCrearFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearFactor", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearFactor")
    @WebMethod(action = "wsCrearFactor")
    @ResponseWrapper(localName = "wsCrearFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearFactorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearFactor(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "unidad", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String unidad,
        @WebParam(name = "valorMin", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valorMin,
        @WebParam(name = "valorMax", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valorMax,
        @WebParam(name = "umbral", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger umbral
    );

    @WebResult(name = "wsAgregarSensorPosicionActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarSensorPosicionActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarSensorPosicionActuadorAvance")
    @WebMethod(action = "wsAgregarSensorPosicionActuadorAvance")
    @ResponseWrapper(localName = "wsAgregarSensorPosicionActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarSensorPosicionActuadorAvanceResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsAgregarSensorPosicionActuadorAvance(
        @WebParam(name = "idSensor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idSensor,
        @WebParam(name = "idActuadorAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idActuadorAvance,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion
    );

    @WebResult(name = "wsEliminarFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarFactor", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarFactor")
    @WebMethod(action = "wsEliminarFactor")
    @ResponseWrapper(localName = "wsEliminarFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarFactorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsEliminarFactor(
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsReestablecerActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsReestablecerActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsReestablecerActuadorAvance")
    @WebMethod(action = "wsReestablecerActuadorAvance")
    @ResponseWrapper(localName = "wsReestablecerActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsReestablecerActuadorAvanceResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsReestablecerActuadorAvance(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion
    );

    @WebResult(name = "wsAgregarPosicionActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarPosicionActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarPosicionActuadorAvance")
    @WebMethod(action = "wsAgregarPosicionActuadorAvance")
    @ResponseWrapper(localName = "wsAgregarPosicionActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarPosicionActuadorAvanceResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsAgregarPosicionActuadorAvance(
        @WebParam(name = "idActuadorAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idActuadorAvance,
        @WebParam(name = "numeroPosicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger numeroPosicion,
        @WebParam(name = "descripcion", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String descripcion,
        @WebParam(name = "valor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger valor
    );

    @WebResult(name = "wsObtenerDatosPlacaResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsObtenerDatosPlaca", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsObtenerDatosPlaca")
    @WebMethod(action = "wsObtenerDatosPlaca")
    @ResponseWrapper(localName = "wsObtenerDatosPlacaResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsObtenerDatosPlacaResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoDatosPlacaWS wsObtenerDatosPlaca(
        @WebParam(name = "temp", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger temp
    );

    @WebResult(name = "wsCrearPlacaAuxiliarResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearPlacaAuxiliar", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearPlacaAuxiliar")
    @WebMethod(action = "wsCrearPlacaAuxiliar")
    @ResponseWrapper(localName = "wsCrearPlacaAuxiliarResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearPlacaAuxiliarResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearPlacaAuxiliar(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "nroSerie", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nroSerie,
        @WebParam(name = "idTipoPlaca", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPlaca,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre
    );

    @WebResult(name = "wsCrearTipoActuadorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearTipoActuador", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearTipoActuador")
    @WebMethod(action = "wsCrearTipoActuador")
    @ResponseWrapper(localName = "wsCrearTipoActuadorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearTipoActuadorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearTipoActuador(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre
    );

    @WebResult(name = "wsAgregarFilaPerfilActivacionResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAgregarFilaPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarFilaPerfilActivacion")
    @WebMethod(action = "wsAgregarFilaPerfilActivacion")
    @ResponseWrapper(localName = "wsAgregarFilaPerfilActivacionResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAgregarFilaPerfilActivacionResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsAgregarFilaPerfilActivacion(
        @WebParam(name = "idPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPerfilActivacion,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores,
        @WebParam(name = "estado", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String estado
    );

    @WebResult(name = "wsEliminarNivelSeveridadResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarNivelSeveridad")
    @WebMethod(action = "wsEliminarNivelSeveridad")
    @ResponseWrapper(localName = "wsEliminarNivelSeveridadResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarNivelSeveridadResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsEliminarNivelSeveridad(
        @WebParam(name = "idNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idNivelSeveridad
    );

    @WebResult(name = "wsAsociarFactorSensorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsAsociarFactorSensor", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAsociarFactorSensor")
    @WebMethod(action = "wsAsociarFactorSensor")
    @ResponseWrapper(localName = "wsAsociarFactorSensorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsAsociarFactorSensorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsAsociarFactorSensor(
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor,
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo
    );

    @WebResult(name = "wsLecturaFactorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsLecturaFactor", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsLecturaFactor")
    @WebMethod(action = "wsLecturaFactor")
    @ResponseWrapper(localName = "wsLecturaFactorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsLecturaFactorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoLecturaWS wsLecturaFactor(
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsEliminarGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarGrupoActuadores")
    @WebMethod(action = "wsEliminarGrupoActuadores")
    @ResponseWrapper(localName = "wsEliminarGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarGrupoActuadoresResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsEliminarGrupoActuadores(
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearActuadorAvanceResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearActuadorAvance", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearActuadorAvance")
    @WebMethod(action = "wsCrearActuadorAvance")
    @ResponseWrapper(localName = "wsCrearActuadorAvanceResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearActuadorAvanceResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearActuadorAvance(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "posicion", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger posicion,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idTipoActuador", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoActuador,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "nroPuertoRetroceso", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuertoRetroceso,
        @WebParam(name = "tipoPuertoRetroceso", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger tipoPuertoRetroceso,
        @WebParam(name = "tiempoEntrePosiciones", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger tiempoEntrePosiciones,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearActuadorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearActuador", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearActuador")
    @WebMethod(action = "wsCrearActuador")
    @ResponseWrapper(localName = "wsCrearActuadorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearActuadorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearActuador(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idTipoActuador", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoActuador,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsCrearGrupoActuadoresResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearGrupoActuadores")
    @WebMethod(action = "wsCrearGrupoActuadores")
    @ResponseWrapper(localName = "wsCrearGrupoActuadoresResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearGrupoActuadoresResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearGrupoActuadores(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "deAvance", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String deAvance
    );

    @WebResult(name = "wsCrearSensorResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearSensor", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearSensor")
    @WebMethod(action = "wsCrearSensor")
    @ResponseWrapper(localName = "wsCrearSensorResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearSensorResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearSensor(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "modelo", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String modelo,
        @WebParam(name = "nroPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger nroPuerto,
        @WebParam(name = "formulaConversion", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String formulaConversion,
        @WebParam(name = "idTipoPuerto", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idTipoPuerto,
        @WebParam(name = "idPlacaPadre", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPlacaPadre,
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor
    );

    @WebResult(name = "wsEliminarFilaPerfilActivacionResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarFilaPerfilActivacion", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarFilaPerfilActivacion")
    @WebMethod(action = "wsEliminarFilaPerfilActivacion")
    @ResponseWrapper(localName = "wsEliminarFilaPerfilActivacionResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarFilaPerfilActivacionResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsEliminarFilaPerfilActivacion(
        @WebParam(name = "idPerfil", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idPerfil,
        @WebParam(name = "idGrupoActuadores", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idGrupoActuadores
    );

    @WebResult(name = "wsEliminarDispositivoResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsEliminarDispositivo", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarDispositivo")
    @WebMethod(action = "wsEliminarDispositivo")
    @ResponseWrapper(localName = "wsEliminarDispositivoResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsEliminarDispositivoResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsEliminarDispositivo(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo
    );

    @WebResult(name = "wsReestablecerEstadoAlertaDispositivoResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsReestablecerEstadoAlertaDispositivo", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsReestablecerEstadoAlertaDispositivo")
    @WebMethod(action = "wsReestablecerEstadoAlertaDispositivo")
    @ResponseWrapper(localName = "wsReestablecerEstadoAlertaDispositivoResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsReestablecerEstadoAlertaDispositivoResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.Mensaje wsReestablecerEstadoAlertaDispositivo(
        @WebParam(name = "idDispositivo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idDispositivo
    );

    @WebResult(name = "wsCrearNivelSeveridadResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearNivelSeveridad", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearNivelSeveridad")
    @WebMethod(action = "wsCrearNivelSeveridad")
    @ResponseWrapper(localName = "wsCrearNivelSeveridadResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearNivelSeveridadResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearNivelSeveridad(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre,
        @WebParam(name = "idFactor", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger idFactor,
        @WebParam(name = "prioridad", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger prioridad,
        @WebParam(name = "rangoMinimo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger rangoMinimo,
        @WebParam(name = "rangoMaximo", targetNamespace = "Comunicacion.Comunicacion")
        java.math.BigInteger rangoMaximo
    );

    @WebResult(name = "wsCrearTipoPlacaResult", targetNamespace = "Comunicacion.Comunicacion")
    @RequestWrapper(localName = "wsCrearTipoPlaca", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearTipoPlaca")
    @WebMethod(action = "wsCrearTipoPlaca")
    @ResponseWrapper(localName = "wsCrearTipoPlacaResponse", targetNamespace = "Comunicacion.Comunicacion", className = "uy.com.ceoyphoibe.SGIA.wsClient.WsCrearTipoPlacaResponse")
    public uy.com.ceoyphoibe.SGIA.wsClient.ResultadoCreacionWS wsCrearTipoPlaca(
        @WebParam(name = "nombre", targetNamespace = "Comunicacion.Comunicacion")
        java.lang.String nombre
    );
}
